/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface TreasuryInterface extends utils.Interface {
  functions: {
    "PERIOD()": FunctionFragment;
    "allocateSeigniorage()": FunctionFragment;
    "bbond()": FunctionFragment;
    "bondDepletionFloorPercent()": FunctionFragment;
    "bootstrapEpochs()": FunctionFragment;
    "bootstrapSupplyExpansionPercent()": FunctionFragment;
    "bshare()": FunctionFragment;
    "buyBonds(uint256,uint256)": FunctionFragment;
    "daoFund()": FunctionFragment;
    "daoFundSharedPercent()": FunctionFragment;
    "devFund()": FunctionFragment;
    "devFundSharedPercent()": FunctionFragment;
    "discountPercent()": FunctionFragment;
    "epoch()": FunctionFragment;
    "epochSupplyContractionLeft()": FunctionFragment;
    "getBondDiscountRate()": FunctionFragment;
    "getBondPremiumRate()": FunctionFragment;
    "getBurnableKittyLeft()": FunctionFragment;
    "getKittyCirculatingSupply()": FunctionFragment;
    "getKittyPrice()": FunctionFragment;
    "getKittyUpdatedPrice()": FunctionFragment;
    "getRedeemableBonds()": FunctionFragment;
    "getReserve()": FunctionFragment;
    "governanceRecoverUnsupported(address,uint256,address)": FunctionFragment;
    "initialize(address,address,address,address,address,uint256)": FunctionFragment;
    "initialized()": FunctionFragment;
    "isInitialized()": FunctionFragment;
    "kitty()": FunctionFragment;
    "kittyOracle()": FunctionFragment;
    "kittyPriceCeiling()": FunctionFragment;
    "kittyPriceOne()": FunctionFragment;
    "maxDebtRatioPercent()": FunctionFragment;
    "maxDiscountRate()": FunctionFragment;
    "maxExpansionTiers(uint256)": FunctionFragment;
    "maxPremiumRate()": FunctionFragment;
    "maxSupplyContractionPercent()": FunctionFragment;
    "maxSupplyExpansionPercent()": FunctionFragment;
    "mintingFactorForPayingDebt()": FunctionFragment;
    "nextEpochPoint()": FunctionFragment;
    "nursery()": FunctionFragment;
    "nurseryAllocateSeigniorage(uint256)": FunctionFragment;
    "nurseryGovernanceRecoverUnsupported(address,uint256,address)": FunctionFragment;
    "nurserySetLockUp(uint256,uint256)": FunctionFragment;
    "nurserySetOperator(address)": FunctionFragment;
    "operator()": FunctionFragment;
    "premiumPercent()": FunctionFragment;
    "premiumThreshold()": FunctionFragment;
    "previousEpochKittyPrice()": FunctionFragment;
    "redeemBonds(uint256,uint256)": FunctionFragment;
    "seigniorageExpansionFloorPercent()": FunctionFragment;
    "seigniorageSaved()": FunctionFragment;
    "setBondDepletionFloorPercent(uint256)": FunctionFragment;
    "setBootstrap(uint256,uint256)": FunctionFragment;
    "setDiscountPercent(uint256)": FunctionFragment;
    "setExtraFunds(address,uint256,address,uint256,address,uint256)": FunctionFragment;
    "setKittyOracle(address)": FunctionFragment;
    "setKittyPriceCeiling(uint256)": FunctionFragment;
    "setMaxDebtRatioPercent(uint256)": FunctionFragment;
    "setMaxDiscountRate(uint256)": FunctionFragment;
    "setMaxExpansionTiersEntry(uint8,uint256)": FunctionFragment;
    "setMaxPremiumRate(uint256)": FunctionFragment;
    "setMaxSupplyContractionPercent(uint256)": FunctionFragment;
    "setMaxSupplyExpansionPercents(uint256)": FunctionFragment;
    "setMintingFactorForPayingDebt(uint256)": FunctionFragment;
    "setNursery(address)": FunctionFragment;
    "setOperator(address)": FunctionFragment;
    "setPremiumPercent(uint256)": FunctionFragment;
    "setPremiumThreshold(uint256)": FunctionFragment;
    "setSupplyTiersEntry(uint8,uint256)": FunctionFragment;
    "startTime()": FunctionFragment;
    "supplyTiers(uint256)": FunctionFragment;
    "team1Fund()": FunctionFragment;
    "team1FundSharedPercent()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "PERIOD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allocateSeigniorage",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bbond", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bondDepletionFloorPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bootstrapEpochs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bootstrapSupplyExpansionPercent",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bshare", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "buyBonds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "daoFund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "daoFundSharedPercent",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "devFund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "devFundSharedPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "discountPercent",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "epoch", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "epochSupplyContractionLeft",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBondDiscountRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBondPremiumRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBurnableKittyLeft",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getKittyCirculatingSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getKittyPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getKittyUpdatedPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRedeemableBonds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReserve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governanceRecoverUnsupported",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "kitty", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "kittyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "kittyPriceCeiling",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "kittyPriceOne",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxDebtRatioPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxDiscountRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxExpansionTiers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxPremiumRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxSupplyContractionPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxSupplyExpansionPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintingFactorForPayingDebt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextEpochPoint",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nursery", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nurseryAllocateSeigniorage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nurseryGovernanceRecoverUnsupported",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "nurserySetLockUp",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nurserySetOperator",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "premiumPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "premiumThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "previousEpochKittyPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redeemBonds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "seigniorageExpansionFloorPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seigniorageSaved",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBondDepletionFloorPercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBootstrap",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDiscountPercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setExtraFunds",
    values: [string, BigNumberish, string, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setKittyOracle",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setKittyPriceCeiling",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxDebtRatioPercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxDiscountRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxExpansionTiersEntry",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxPremiumRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxSupplyContractionPercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxSupplyExpansionPercents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMintingFactorForPayingDebt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setNursery", values: [string]): string;
  encodeFunctionData(functionFragment: "setOperator", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setPremiumPercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPremiumThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSupplyTiersEntry",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "startTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supplyTiers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "team1Fund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "team1FundSharedPercent",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "PERIOD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allocateSeigniorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bbond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bondDepletionFloorPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bootstrapEpochs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bootstrapSupplyExpansionPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bshare", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyBonds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "daoFund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "daoFundSharedPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "devFund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "devFundSharedPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "discountPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "epoch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "epochSupplyContractionLeft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBondDiscountRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBondPremiumRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBurnableKittyLeft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getKittyCirculatingSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getKittyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getKittyUpdatedPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRedeemableBonds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getReserve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "governanceRecoverUnsupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "kitty", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "kittyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "kittyPriceCeiling",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "kittyPriceOne",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxDebtRatioPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxDiscountRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxExpansionTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxPremiumRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxSupplyContractionPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxSupplyExpansionPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintingFactorForPayingDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextEpochPoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nursery", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nurseryAllocateSeigniorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nurseryGovernanceRecoverUnsupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nurserySetLockUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nurserySetOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "premiumPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "premiumThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previousEpochKittyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemBonds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seigniorageExpansionFloorPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seigniorageSaved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBondDepletionFloorPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBootstrap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDiscountPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExtraFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKittyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKittyPriceCeiling",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxDebtRatioPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxDiscountRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxExpansionTiersEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxPremiumRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxSupplyContractionPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxSupplyExpansionPercents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMintingFactorForPayingDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setNursery", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPremiumPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPremiumThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSupplyTiersEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supplyTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "team1Fund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "team1FundSharedPercent",
    data: BytesLike
  ): Result;

  events: {
    "BoughtBonds(address,uint256,uint256)": EventFragment;
    "BurnedBonds(address,uint256)": EventFragment;
    "DaoFundFunded(uint256,uint256)": EventFragment;
    "DevFundFunded(uint256,uint256)": EventFragment;
    "Initialized(address,uint256)": EventFragment;
    "NurseryFunded(uint256,uint256)": EventFragment;
    "RedeemedBonds(address,uint256,uint256)": EventFragment;
    "TeamFundFunded(uint256,uint256)": EventFragment;
    "TreasuryFunded(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BoughtBonds"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BurnedBonds"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DaoFundFunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DevFundFunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NurseryFunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RedeemedBonds"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TeamFundFunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TreasuryFunded"): EventFragment;
}

export type BoughtBondsEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { from: string; kittyAmount: BigNumber; bondAmount: BigNumber }
>;

export type BoughtBondsEventFilter = TypedEventFilter<BoughtBondsEvent>;

export type BurnedBondsEvent = TypedEvent<
  [string, BigNumber],
  { from: string; bondAmount: BigNumber }
>;

export type BurnedBondsEventFilter = TypedEventFilter<BurnedBondsEvent>;

export type DaoFundFundedEvent = TypedEvent<
  [BigNumber, BigNumber],
  { timestamp: BigNumber; seigniorage: BigNumber }
>;

export type DaoFundFundedEventFilter = TypedEventFilter<DaoFundFundedEvent>;

export type DevFundFundedEvent = TypedEvent<
  [BigNumber, BigNumber],
  { timestamp: BigNumber; seigniorage: BigNumber }
>;

export type DevFundFundedEventFilter = TypedEventFilter<DevFundFundedEvent>;

export type InitializedEvent = TypedEvent<
  [string, BigNumber],
  { executor: string; at: BigNumber }
>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export type NurseryFundedEvent = TypedEvent<
  [BigNumber, BigNumber],
  { timestamp: BigNumber; seigniorage: BigNumber }
>;

export type NurseryFundedEventFilter = TypedEventFilter<NurseryFundedEvent>;

export type RedeemedBondsEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { from: string; kittyAmount: BigNumber; bondAmount: BigNumber }
>;

export type RedeemedBondsEventFilter = TypedEventFilter<RedeemedBondsEvent>;

export type TeamFundFundedEvent = TypedEvent<
  [BigNumber, BigNumber],
  { timestamp: BigNumber; seigniorage: BigNumber }
>;

export type TeamFundFundedEventFilter = TypedEventFilter<TeamFundFundedEvent>;

export type TreasuryFundedEvent = TypedEvent<
  [BigNumber, BigNumber],
  { timestamp: BigNumber; seigniorage: BigNumber }
>;

export type TreasuryFundedEventFilter = TypedEventFilter<TreasuryFundedEvent>;

export interface Treasury extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TreasuryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    PERIOD(overrides?: CallOverrides): Promise<[BigNumber]>;

    allocateSeigniorage(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    bbond(overrides?: CallOverrides): Promise<[string]>;

    bondDepletionFloorPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    bootstrapEpochs(overrides?: CallOverrides): Promise<[BigNumber]>;

    bootstrapSupplyExpansionPercent(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    bshare(overrides?: CallOverrides): Promise<[string]>;

    buyBonds(
      _kittyAmount: BigNumberish,
      targetPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    daoFund(overrides?: CallOverrides): Promise<[string]>;

    daoFundSharedPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    devFund(overrides?: CallOverrides): Promise<[string]>;

    devFundSharedPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    discountPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    epoch(overrides?: CallOverrides): Promise<[BigNumber]>;

    epochSupplyContractionLeft(overrides?: CallOverrides): Promise<[BigNumber]>;

    getBondDiscountRate(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _rate: BigNumber }>;

    getBondPremiumRate(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _rate: BigNumber }>;

    getBurnableKittyLeft(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _burnableKittyLeft: BigNumber }>;

    getKittyCirculatingSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    getKittyPrice(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { kittyPrice: BigNumber }>;

    getKittyUpdatedPrice(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _kittyPrice: BigNumber }>;

    getRedeemableBonds(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _redeemableBonds: BigNumber }>;

    getReserve(overrides?: CallOverrides): Promise<[BigNumber]>;

    governanceRecoverUnsupported(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialize(
      _kitty: string,
      _bbond: string,
      _bshare: string,
      _kittyOracle: string,
      _nursery: string,
      _startTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialized(overrides?: CallOverrides): Promise<[boolean]>;

    isInitialized(overrides?: CallOverrides): Promise<[boolean]>;

    kitty(overrides?: CallOverrides): Promise<[string]>;

    kittyOracle(overrides?: CallOverrides): Promise<[string]>;

    kittyPriceCeiling(overrides?: CallOverrides): Promise<[BigNumber]>;

    kittyPriceOne(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxDebtRatioPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxDiscountRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxExpansionTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    maxPremiumRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxSupplyContractionPercent(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    maxSupplyExpansionPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    mintingFactorForPayingDebt(overrides?: CallOverrides): Promise<[BigNumber]>;

    nextEpochPoint(overrides?: CallOverrides): Promise<[BigNumber]>;

    nursery(overrides?: CallOverrides): Promise<[string]>;

    nurseryAllocateSeigniorage(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    nurseryGovernanceRecoverUnsupported(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    nurserySetLockUp(
      _withdrawLockupEpochs: BigNumberish,
      _rewardLockupEpochs: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    nurserySetOperator(
      _operator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    operator(overrides?: CallOverrides): Promise<[string]>;

    premiumPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    premiumThreshold(overrides?: CallOverrides): Promise<[BigNumber]>;

    previousEpochKittyPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    redeemBonds(
      _bondAmount: BigNumberish,
      targetPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    seigniorageExpansionFloorPercent(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    seigniorageSaved(overrides?: CallOverrides): Promise<[BigNumber]>;

    setBondDepletionFloorPercent(
      _bondDepletionFloorPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBootstrap(
      _bootstrapEpochs: BigNumberish,
      _bootstrapSupplyExpansionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDiscountPercent(
      _discountPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setExtraFunds(
      _daoFund: string,
      _daoFundSharedPercent: BigNumberish,
      _devFund: string,
      _devFundSharedPercent: BigNumberish,
      _team1Fund: string,
      _team1FundSharedPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setKittyOracle(
      _kittyOracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setKittyPriceCeiling(
      _kittyPriceCeiling: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxDebtRatioPercent(
      _maxDebtRatioPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxDiscountRate(
      _maxDiscountRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxExpansionTiersEntry(
      _index: BigNumberish,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxPremiumRate(
      _maxPremiumRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxSupplyContractionPercent(
      _maxSupplyContractionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxSupplyExpansionPercents(
      _maxSupplyExpansionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMintingFactorForPayingDebt(
      _mintingFactorForPayingDebt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setNursery(
      _nursery: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOperator(
      _operator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPremiumPercent(
      _premiumPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPremiumThreshold(
      _premiumThreshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSupplyTiersEntry(
      _index: BigNumberish,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    startTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    supplyTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    team1Fund(overrides?: CallOverrides): Promise<[string]>;

    team1FundSharedPercent(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  PERIOD(overrides?: CallOverrides): Promise<BigNumber>;

  allocateSeigniorage(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  bbond(overrides?: CallOverrides): Promise<string>;

  bondDepletionFloorPercent(overrides?: CallOverrides): Promise<BigNumber>;

  bootstrapEpochs(overrides?: CallOverrides): Promise<BigNumber>;

  bootstrapSupplyExpansionPercent(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  bshare(overrides?: CallOverrides): Promise<string>;

  buyBonds(
    _kittyAmount: BigNumberish,
    targetPrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  daoFund(overrides?: CallOverrides): Promise<string>;

  daoFundSharedPercent(overrides?: CallOverrides): Promise<BigNumber>;

  devFund(overrides?: CallOverrides): Promise<string>;

  devFundSharedPercent(overrides?: CallOverrides): Promise<BigNumber>;

  discountPercent(overrides?: CallOverrides): Promise<BigNumber>;

  epoch(overrides?: CallOverrides): Promise<BigNumber>;

  epochSupplyContractionLeft(overrides?: CallOverrides): Promise<BigNumber>;

  getBondDiscountRate(overrides?: CallOverrides): Promise<BigNumber>;

  getBondPremiumRate(overrides?: CallOverrides): Promise<BigNumber>;

  getBurnableKittyLeft(overrides?: CallOverrides): Promise<BigNumber>;

  getKittyCirculatingSupply(overrides?: CallOverrides): Promise<BigNumber>;

  getKittyPrice(overrides?: CallOverrides): Promise<BigNumber>;

  getKittyUpdatedPrice(overrides?: CallOverrides): Promise<BigNumber>;

  getRedeemableBonds(overrides?: CallOverrides): Promise<BigNumber>;

  getReserve(overrides?: CallOverrides): Promise<BigNumber>;

  governanceRecoverUnsupported(
    _token: string,
    _amount: BigNumberish,
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialize(
    _kitty: string,
    _bbond: string,
    _bshare: string,
    _kittyOracle: string,
    _nursery: string,
    _startTime: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialized(overrides?: CallOverrides): Promise<boolean>;

  isInitialized(overrides?: CallOverrides): Promise<boolean>;

  kitty(overrides?: CallOverrides): Promise<string>;

  kittyOracle(overrides?: CallOverrides): Promise<string>;

  kittyPriceCeiling(overrides?: CallOverrides): Promise<BigNumber>;

  kittyPriceOne(overrides?: CallOverrides): Promise<BigNumber>;

  maxDebtRatioPercent(overrides?: CallOverrides): Promise<BigNumber>;

  maxDiscountRate(overrides?: CallOverrides): Promise<BigNumber>;

  maxExpansionTiers(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  maxPremiumRate(overrides?: CallOverrides): Promise<BigNumber>;

  maxSupplyContractionPercent(overrides?: CallOverrides): Promise<BigNumber>;

  maxSupplyExpansionPercent(overrides?: CallOverrides): Promise<BigNumber>;

  mintingFactorForPayingDebt(overrides?: CallOverrides): Promise<BigNumber>;

  nextEpochPoint(overrides?: CallOverrides): Promise<BigNumber>;

  nursery(overrides?: CallOverrides): Promise<string>;

  nurseryAllocateSeigniorage(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  nurseryGovernanceRecoverUnsupported(
    _token: string,
    _amount: BigNumberish,
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  nurserySetLockUp(
    _withdrawLockupEpochs: BigNumberish,
    _rewardLockupEpochs: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  nurserySetOperator(
    _operator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  operator(overrides?: CallOverrides): Promise<string>;

  premiumPercent(overrides?: CallOverrides): Promise<BigNumber>;

  premiumThreshold(overrides?: CallOverrides): Promise<BigNumber>;

  previousEpochKittyPrice(overrides?: CallOverrides): Promise<BigNumber>;

  redeemBonds(
    _bondAmount: BigNumberish,
    targetPrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  seigniorageExpansionFloorPercent(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  seigniorageSaved(overrides?: CallOverrides): Promise<BigNumber>;

  setBondDepletionFloorPercent(
    _bondDepletionFloorPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBootstrap(
    _bootstrapEpochs: BigNumberish,
    _bootstrapSupplyExpansionPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDiscountPercent(
    _discountPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setExtraFunds(
    _daoFund: string,
    _daoFundSharedPercent: BigNumberish,
    _devFund: string,
    _devFundSharedPercent: BigNumberish,
    _team1Fund: string,
    _team1FundSharedPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setKittyOracle(
    _kittyOracle: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setKittyPriceCeiling(
    _kittyPriceCeiling: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxDebtRatioPercent(
    _maxDebtRatioPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxDiscountRate(
    _maxDiscountRate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxExpansionTiersEntry(
    _index: BigNumberish,
    _value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxPremiumRate(
    _maxPremiumRate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxSupplyContractionPercent(
    _maxSupplyContractionPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxSupplyExpansionPercents(
    _maxSupplyExpansionPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMintingFactorForPayingDebt(
    _mintingFactorForPayingDebt: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setNursery(
    _nursery: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOperator(
    _operator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPremiumPercent(
    _premiumPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPremiumThreshold(
    _premiumThreshold: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSupplyTiersEntry(
    _index: BigNumberish,
    _value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  startTime(overrides?: CallOverrides): Promise<BigNumber>;

  supplyTiers(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  team1Fund(overrides?: CallOverrides): Promise<string>;

  team1FundSharedPercent(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    PERIOD(overrides?: CallOverrides): Promise<BigNumber>;

    allocateSeigniorage(overrides?: CallOverrides): Promise<void>;

    bbond(overrides?: CallOverrides): Promise<string>;

    bondDepletionFloorPercent(overrides?: CallOverrides): Promise<BigNumber>;

    bootstrapEpochs(overrides?: CallOverrides): Promise<BigNumber>;

    bootstrapSupplyExpansionPercent(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bshare(overrides?: CallOverrides): Promise<string>;

    buyBonds(
      _kittyAmount: BigNumberish,
      targetPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    daoFund(overrides?: CallOverrides): Promise<string>;

    daoFundSharedPercent(overrides?: CallOverrides): Promise<BigNumber>;

    devFund(overrides?: CallOverrides): Promise<string>;

    devFundSharedPercent(overrides?: CallOverrides): Promise<BigNumber>;

    discountPercent(overrides?: CallOverrides): Promise<BigNumber>;

    epoch(overrides?: CallOverrides): Promise<BigNumber>;

    epochSupplyContractionLeft(overrides?: CallOverrides): Promise<BigNumber>;

    getBondDiscountRate(overrides?: CallOverrides): Promise<BigNumber>;

    getBondPremiumRate(overrides?: CallOverrides): Promise<BigNumber>;

    getBurnableKittyLeft(overrides?: CallOverrides): Promise<BigNumber>;

    getKittyCirculatingSupply(overrides?: CallOverrides): Promise<BigNumber>;

    getKittyPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getKittyUpdatedPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getRedeemableBonds(overrides?: CallOverrides): Promise<BigNumber>;

    getReserve(overrides?: CallOverrides): Promise<BigNumber>;

    governanceRecoverUnsupported(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    initialize(
      _kitty: string,
      _bbond: string,
      _bshare: string,
      _kittyOracle: string,
      _nursery: string,
      _startTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    initialized(overrides?: CallOverrides): Promise<boolean>;

    isInitialized(overrides?: CallOverrides): Promise<boolean>;

    kitty(overrides?: CallOverrides): Promise<string>;

    kittyOracle(overrides?: CallOverrides): Promise<string>;

    kittyPriceCeiling(overrides?: CallOverrides): Promise<BigNumber>;

    kittyPriceOne(overrides?: CallOverrides): Promise<BigNumber>;

    maxDebtRatioPercent(overrides?: CallOverrides): Promise<BigNumber>;

    maxDiscountRate(overrides?: CallOverrides): Promise<BigNumber>;

    maxExpansionTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxPremiumRate(overrides?: CallOverrides): Promise<BigNumber>;

    maxSupplyContractionPercent(overrides?: CallOverrides): Promise<BigNumber>;

    maxSupplyExpansionPercent(overrides?: CallOverrides): Promise<BigNumber>;

    mintingFactorForPayingDebt(overrides?: CallOverrides): Promise<BigNumber>;

    nextEpochPoint(overrides?: CallOverrides): Promise<BigNumber>;

    nursery(overrides?: CallOverrides): Promise<string>;

    nurseryAllocateSeigniorage(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    nurseryGovernanceRecoverUnsupported(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    nurserySetLockUp(
      _withdrawLockupEpochs: BigNumberish,
      _rewardLockupEpochs: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    nurserySetOperator(
      _operator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    operator(overrides?: CallOverrides): Promise<string>;

    premiumPercent(overrides?: CallOverrides): Promise<BigNumber>;

    premiumThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    previousEpochKittyPrice(overrides?: CallOverrides): Promise<BigNumber>;

    redeemBonds(
      _bondAmount: BigNumberish,
      targetPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    seigniorageExpansionFloorPercent(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seigniorageSaved(overrides?: CallOverrides): Promise<BigNumber>;

    setBondDepletionFloorPercent(
      _bondDepletionFloorPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setBootstrap(
      _bootstrapEpochs: BigNumberish,
      _bootstrapSupplyExpansionPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setDiscountPercent(
      _discountPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setExtraFunds(
      _daoFund: string,
      _daoFundSharedPercent: BigNumberish,
      _devFund: string,
      _devFundSharedPercent: BigNumberish,
      _team1Fund: string,
      _team1FundSharedPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setKittyOracle(
      _kittyOracle: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setKittyPriceCeiling(
      _kittyPriceCeiling: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxDebtRatioPercent(
      _maxDebtRatioPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxDiscountRate(
      _maxDiscountRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxExpansionTiersEntry(
      _index: BigNumberish,
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setMaxPremiumRate(
      _maxPremiumRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxSupplyContractionPercent(
      _maxSupplyContractionPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxSupplyExpansionPercents(
      _maxSupplyExpansionPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMintingFactorForPayingDebt(
      _mintingFactorForPayingDebt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setNursery(_nursery: string, overrides?: CallOverrides): Promise<void>;

    setOperator(_operator: string, overrides?: CallOverrides): Promise<void>;

    setPremiumPercent(
      _premiumPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setPremiumThreshold(
      _premiumThreshold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setSupplyTiersEntry(
      _index: BigNumberish,
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    startTime(overrides?: CallOverrides): Promise<BigNumber>;

    supplyTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    team1Fund(overrides?: CallOverrides): Promise<string>;

    team1FundSharedPercent(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "BoughtBonds(address,uint256,uint256)"(
      from?: string | null,
      kittyAmount?: null,
      bondAmount?: null
    ): BoughtBondsEventFilter;
    BoughtBonds(
      from?: string | null,
      kittyAmount?: null,
      bondAmount?: null
    ): BoughtBondsEventFilter;

    "BurnedBonds(address,uint256)"(
      from?: string | null,
      bondAmount?: null
    ): BurnedBondsEventFilter;
    BurnedBonds(
      from?: string | null,
      bondAmount?: null
    ): BurnedBondsEventFilter;

    "DaoFundFunded(uint256,uint256)"(
      timestamp?: null,
      seigniorage?: null
    ): DaoFundFundedEventFilter;
    DaoFundFunded(
      timestamp?: null,
      seigniorage?: null
    ): DaoFundFundedEventFilter;

    "DevFundFunded(uint256,uint256)"(
      timestamp?: null,
      seigniorage?: null
    ): DevFundFundedEventFilter;
    DevFundFunded(
      timestamp?: null,
      seigniorage?: null
    ): DevFundFundedEventFilter;

    "Initialized(address,uint256)"(
      executor?: string | null,
      at?: null
    ): InitializedEventFilter;
    Initialized(executor?: string | null, at?: null): InitializedEventFilter;

    "NurseryFunded(uint256,uint256)"(
      timestamp?: null,
      seigniorage?: null
    ): NurseryFundedEventFilter;
    NurseryFunded(
      timestamp?: null,
      seigniorage?: null
    ): NurseryFundedEventFilter;

    "RedeemedBonds(address,uint256,uint256)"(
      from?: string | null,
      kittyAmount?: null,
      bondAmount?: null
    ): RedeemedBondsEventFilter;
    RedeemedBonds(
      from?: string | null,
      kittyAmount?: null,
      bondAmount?: null
    ): RedeemedBondsEventFilter;

    "TeamFundFunded(uint256,uint256)"(
      timestamp?: null,
      seigniorage?: null
    ): TeamFundFundedEventFilter;
    TeamFundFunded(
      timestamp?: null,
      seigniorage?: null
    ): TeamFundFundedEventFilter;

    "TreasuryFunded(uint256,uint256)"(
      timestamp?: null,
      seigniorage?: null
    ): TreasuryFundedEventFilter;
    TreasuryFunded(
      timestamp?: null,
      seigniorage?: null
    ): TreasuryFundedEventFilter;
  };

  estimateGas: {
    PERIOD(overrides?: CallOverrides): Promise<BigNumber>;

    allocateSeigniorage(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    bbond(overrides?: CallOverrides): Promise<BigNumber>;

    bondDepletionFloorPercent(overrides?: CallOverrides): Promise<BigNumber>;

    bootstrapEpochs(overrides?: CallOverrides): Promise<BigNumber>;

    bootstrapSupplyExpansionPercent(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bshare(overrides?: CallOverrides): Promise<BigNumber>;

    buyBonds(
      _kittyAmount: BigNumberish,
      targetPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    daoFund(overrides?: CallOverrides): Promise<BigNumber>;

    daoFundSharedPercent(overrides?: CallOverrides): Promise<BigNumber>;

    devFund(overrides?: CallOverrides): Promise<BigNumber>;

    devFundSharedPercent(overrides?: CallOverrides): Promise<BigNumber>;

    discountPercent(overrides?: CallOverrides): Promise<BigNumber>;

    epoch(overrides?: CallOverrides): Promise<BigNumber>;

    epochSupplyContractionLeft(overrides?: CallOverrides): Promise<BigNumber>;

    getBondDiscountRate(overrides?: CallOverrides): Promise<BigNumber>;

    getBondPremiumRate(overrides?: CallOverrides): Promise<BigNumber>;

    getBurnableKittyLeft(overrides?: CallOverrides): Promise<BigNumber>;

    getKittyCirculatingSupply(overrides?: CallOverrides): Promise<BigNumber>;

    getKittyPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getKittyUpdatedPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getRedeemableBonds(overrides?: CallOverrides): Promise<BigNumber>;

    getReserve(overrides?: CallOverrides): Promise<BigNumber>;

    governanceRecoverUnsupported(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialize(
      _kitty: string,
      _bbond: string,
      _bshare: string,
      _kittyOracle: string,
      _nursery: string,
      _startTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialized(overrides?: CallOverrides): Promise<BigNumber>;

    isInitialized(overrides?: CallOverrides): Promise<BigNumber>;

    kitty(overrides?: CallOverrides): Promise<BigNumber>;

    kittyOracle(overrides?: CallOverrides): Promise<BigNumber>;

    kittyPriceCeiling(overrides?: CallOverrides): Promise<BigNumber>;

    kittyPriceOne(overrides?: CallOverrides): Promise<BigNumber>;

    maxDebtRatioPercent(overrides?: CallOverrides): Promise<BigNumber>;

    maxDiscountRate(overrides?: CallOverrides): Promise<BigNumber>;

    maxExpansionTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxPremiumRate(overrides?: CallOverrides): Promise<BigNumber>;

    maxSupplyContractionPercent(overrides?: CallOverrides): Promise<BigNumber>;

    maxSupplyExpansionPercent(overrides?: CallOverrides): Promise<BigNumber>;

    mintingFactorForPayingDebt(overrides?: CallOverrides): Promise<BigNumber>;

    nextEpochPoint(overrides?: CallOverrides): Promise<BigNumber>;

    nursery(overrides?: CallOverrides): Promise<BigNumber>;

    nurseryAllocateSeigniorage(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    nurseryGovernanceRecoverUnsupported(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    nurserySetLockUp(
      _withdrawLockupEpochs: BigNumberish,
      _rewardLockupEpochs: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    nurserySetOperator(
      _operator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    operator(overrides?: CallOverrides): Promise<BigNumber>;

    premiumPercent(overrides?: CallOverrides): Promise<BigNumber>;

    premiumThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    previousEpochKittyPrice(overrides?: CallOverrides): Promise<BigNumber>;

    redeemBonds(
      _bondAmount: BigNumberish,
      targetPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    seigniorageExpansionFloorPercent(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seigniorageSaved(overrides?: CallOverrides): Promise<BigNumber>;

    setBondDepletionFloorPercent(
      _bondDepletionFloorPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBootstrap(
      _bootstrapEpochs: BigNumberish,
      _bootstrapSupplyExpansionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDiscountPercent(
      _discountPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setExtraFunds(
      _daoFund: string,
      _daoFundSharedPercent: BigNumberish,
      _devFund: string,
      _devFundSharedPercent: BigNumberish,
      _team1Fund: string,
      _team1FundSharedPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setKittyOracle(
      _kittyOracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setKittyPriceCeiling(
      _kittyPriceCeiling: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxDebtRatioPercent(
      _maxDebtRatioPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxDiscountRate(
      _maxDiscountRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxExpansionTiersEntry(
      _index: BigNumberish,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxPremiumRate(
      _maxPremiumRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxSupplyContractionPercent(
      _maxSupplyContractionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxSupplyExpansionPercents(
      _maxSupplyExpansionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMintingFactorForPayingDebt(
      _mintingFactorForPayingDebt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setNursery(
      _nursery: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOperator(
      _operator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPremiumPercent(
      _premiumPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPremiumThreshold(
      _premiumThreshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSupplyTiersEntry(
      _index: BigNumberish,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    startTime(overrides?: CallOverrides): Promise<BigNumber>;

    supplyTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    team1Fund(overrides?: CallOverrides): Promise<BigNumber>;

    team1FundSharedPercent(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    PERIOD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    allocateSeigniorage(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    bbond(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bondDepletionFloorPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bootstrapEpochs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bootstrapSupplyExpansionPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bshare(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    buyBonds(
      _kittyAmount: BigNumberish,
      targetPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    daoFund(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    daoFundSharedPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    devFund(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    devFundSharedPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    discountPercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    epoch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    epochSupplyContractionLeft(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBondDiscountRate(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBondPremiumRate(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBurnableKittyLeft(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getKittyCirculatingSupply(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getKittyPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getKittyUpdatedPrice(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRedeemableBonds(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReserve(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governanceRecoverUnsupported(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      _kitty: string,
      _bbond: string,
      _bshare: string,
      _kittyOracle: string,
      _nursery: string,
      _startTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialized(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isInitialized(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    kitty(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    kittyOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    kittyPriceCeiling(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    kittyPriceOne(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxDebtRatioPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxDiscountRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxExpansionTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxPremiumRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxSupplyContractionPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxSupplyExpansionPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mintingFactorForPayingDebt(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nextEpochPoint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nursery(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nurseryAllocateSeigniorage(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    nurseryGovernanceRecoverUnsupported(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    nurserySetLockUp(
      _withdrawLockupEpochs: BigNumberish,
      _rewardLockupEpochs: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    nurserySetOperator(
      _operator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    operator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    premiumPercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    premiumThreshold(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    previousEpochKittyPrice(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    redeemBonds(
      _bondAmount: BigNumberish,
      targetPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    seigniorageExpansionFloorPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    seigniorageSaved(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setBondDepletionFloorPercent(
      _bondDepletionFloorPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBootstrap(
      _bootstrapEpochs: BigNumberish,
      _bootstrapSupplyExpansionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDiscountPercent(
      _discountPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setExtraFunds(
      _daoFund: string,
      _daoFundSharedPercent: BigNumberish,
      _devFund: string,
      _devFundSharedPercent: BigNumberish,
      _team1Fund: string,
      _team1FundSharedPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setKittyOracle(
      _kittyOracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setKittyPriceCeiling(
      _kittyPriceCeiling: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxDebtRatioPercent(
      _maxDebtRatioPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxDiscountRate(
      _maxDiscountRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxExpansionTiersEntry(
      _index: BigNumberish,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxPremiumRate(
      _maxPremiumRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxSupplyContractionPercent(
      _maxSupplyContractionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxSupplyExpansionPercents(
      _maxSupplyExpansionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMintingFactorForPayingDebt(
      _mintingFactorForPayingDebt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setNursery(
      _nursery: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOperator(
      _operator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPremiumPercent(
      _premiumPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPremiumThreshold(
      _premiumThreshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSupplyTiersEntry(
      _index: BigNumberish,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    startTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    supplyTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    team1Fund(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    team1FundSharedPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
