/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IShare, IShareInterface } from "../IShare";

const _abi = [
  {
    inputs: [],
    name: "claimRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unclaimedTreasuryFund",
    outputs: [
      {
        internalType: "uint256",
        name: "_pending",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IShare__factory {
  static readonly abi = _abi;
  static createInterface(): IShareInterface {
    return new utils.Interface(_abi) as IShareInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IShare {
    return new Contract(address, _abi, signerOrProvider) as IShare;
  }
}
