/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISimpleERCFund,
  ISimpleERCFundInterface,
} from "../ISimpleERCFund";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISimpleERCFund__factory {
  static readonly abi = _abi;
  static createInterface(): ISimpleERCFundInterface {
    return new utils.Interface(_abi) as ISimpleERCFundInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISimpleERCFund {
    return new Contract(address, _abi, signerOrProvider) as ISimpleERCFund;
  }
}
